name: workflow-events
on:
 pull_request:
 workflow_dispatch:
    
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name:  Show the trigger
              run: echo "${{ github.event_name }}"
