name: workflow-events
on:
 push:
 pull_request:
 workflow_dispatch:
    
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name:  Show the trigger
              run: echo "${{ github.event_name }}"
