name: Matrix with Include

on:
 workflow_dispatch:

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node: [14, 16]
        os: [ubuntu-latest]
        include:
          - node: 18
            os: windows-latest
            custom: "extra test"

    steps:
      - name: Show matrix values
        run: |
          echo "Node version: ${{ matrix.node }}"
          echo "OS: ${{ matrix.os }}"
          echo "Custom: ${{ matrix.custom }}"
